export const todoType = {
    TODLIST_GET: "TODLIST_GET",
    TODOLIST_ADD: "TODOLIST_ADD",
    TODOLIST_FILTERED: "TODOLIST_FILTERED",
    UPDATE_STATUS: "UPDATE_STATUS",
    // CREATE_TODO: "CREATE_TODO",
    // DELETE_TODO: "DELETE_TODO",
    // UPDATE_STATUS: "UPDATE_STATUS",
    // UPDATE_TODO: "UPDATE_TODO"
}